### ISSUE TITLE
adding a ManyToOne relationship to the user class

### ISSUE THREAD

**Issue by hagaisela** [naturalprogrammer/spring-lemon#9]
Hi,
I added another entity class to my project which is based on lemon-demo, and I am trying to add a ManyToOne relationship between the User class and the new class (LanguageServiceProvider).

User.java:
```
package com.naturalprogrammer.spring.lemondemo.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonView;
import com.naturalprogrammer.spring.lemon.domain.AbstractUser;

@Entity
@Table(name = "usr")
public class User extends AbstractUser<User, Long>
{

	private static final long serialVersionUID = 2716710947175132319L;

	public static final int NAME_MIN = 1;
	public static final int NAME_MAX = 50;

	public User()
	{
	}

	public User(String email, String password, String name)
	{
		this.email = email;
		this.password = password;
		this.name = name;
	}

	@JsonView(SignupInput.class)
	@NotBlank(message = "{blank.name}", groups = { SignUpValidation.class, UpdateValidation.class })
	@Size(min = NAME_MIN, max = NAME_MAX, groups = { SignUpValidation.class, UpdateValidation.class })
	@Column(nullable = false, length = NAME_MAX)
	private String name;

	private LanguageServiceProvider languageServiceProvider;

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@ManyToOne
	@JoinColumn(name = "lspId")
	public LanguageServiceProvider getLanguageServiceProvider()
	{
		return languageServiceProvider;
	}

	public void setLanguageServiceProvider(LanguageServiceProvider languageServiceProvider)
	{
		this.languageServiceProvider = languageServiceProvider;
	}

}

```
LanguageServiceProvider.java:
```
package com.naturalprogrammer.spring.lemondemo.entities;
// Generated Jun 8, 2017 9:59:22 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LanguageServiceProvider generated by hbm2java
 */
@Entity
@Table(name = "language_service_provider")
public class LanguageServiceProvider implements java.io.Serializable
{

	private Long idLanguageServiceProvider;
	private String ivrCode;
	private String name;
	private Set<User> users;

	public LanguageServiceProvider()
	{
	}

	public LanguageServiceProvider(String ivrCode, String name)
	{
		this.ivrCode = ivrCode;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_language_service_provider", unique = true, nullable = false)
	public Long getIdLanguageServiceProvider()
	{
		return this.idLanguageServiceProvider;
	}

	public void setIdLanguageServiceProvider(Long idLanguageServiceProvider)
	{
		this.idLanguageServiceProvider = idLanguageServiceProvider;
	}

	@Column(name = "ivr_code", length = 16)
	public String getIvrCode()
	{
		return this.ivrCode;
	}

	public void setIvrCode(String ivrCode)
	{
		this.ivrCode = ivrCode;
	}

	@Column(name = "name", length = 128)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "languageServiceProvider")
	public Set<User> getUsers()
	{
		return users;
	}

	public void setUsers(Set<User> users)
	{
		this.users = users;
	}
}
```

When the server starts I am getting this exception:

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'language_service_provider' used in key specification without a key length
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468) ~[mysql-connector-java-5.1.41.jar:5.1.41]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-8.5.14.jar:na]
	at com.sun.proxy.$Proxy115.executeUpdate(Unknown Source) ~[na:na]
	at org.hibernate.tool.schema.internal.TargetDatabaseImpl.accept(TargetDatabaseImpl.java:56) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	... 72 common frames omitted


```
I looked inside mysql. For some reason a column named language_service_provider is created inside the usr table instead of lsp_id, and it is created as TINYBLOB instead of BIGINT. Is there any way to change this?

**Comment by hagaisela** [comment]
OK, I found the problem. I put the annotations on the getters, and lemon puts them on the fields. for some reason hibernate doesn't like that. I moved my annontations to the field and it works. Maybe you should write a note about this.

**Comment by naturalprogrammer** [comment]
Thank you, leaving this ticket open so that I'd write a note about this.
